import { Event, Order, Category, WishlistItem, WaitlistEntry } from "./types";

// Categories for filtering
export const categories: Category[] = [
  "Music",
  "Sports",
  "Conference",
  "Theater",
  "Food & Drink",
  "Arts",
  "Other",
];

// Cities for location filtering
export const cities: string[] = [
  "Hanoi",
  "Ho Chi Minh City",
  "Da Nang",
  "Hai Phong",
  "Can Tho",
  "Bien Hoa",
  "Hue",
  "Nha Trang",
  "Buon Ma Thuot",
  "Phan Thiet",
  "Bac Giang",
  "Bac Ninh",
  "Hai Duong",
  "Hung Yen",
  "Nam Dinh",
  "Thai Binh",
  "Vinh Phuc",
  "Ha Long",
  "Vung Tau",
];

export const mockEvents: Event[] = [
  {
    id: "evt-1",
    title: "Summer Music Festival",
    slug: "summer-music-festival",
    category: "Music",
    image: "https://example.com/images/summer-music-festival.jpg",
    description:
      "A vibrant music festival featuring top artists from around the world.",
    venue: "Central Park",
    city: "Hanoi",
    date: "2025-07-15",
    time: "14:00",
    organizerId: "org-1",
    organizerName: "Event Organizers Inc",
    ticketTiers: [
      {
        id: "tier-1",
        name: "General Admission",
        price: 500000,
        available: 100,
        total: 100,
      },
    ],
    policies: {
      refundable: true,
      transferable: true,
    },
    status: "published",
    createdAt: "2025-01-01T00:00:00",
  },
  {
    id: "evt-2",
    title: "Vietnam National Music Awards",
    slug: "vietnam-national-music-awards",
    category: "Music",
    image: "https://example.com/images/vietnam-national-music-awards.jpg",
    description: "An annual event celebrating the best in Vietnamese music.",
    venue: "Hanoi Opera House",
    city: "Hanoi",
    date: "2025-08-20",
    time: "19:00",
    organizerId: "org-1",
    organizerName: "Vietnam Music Association",
    ticketTiers: [
      {
        id: "tier-6",
        name: "Category A",
        price: 800000,
        available: 50,
        total: 50,
      },
    ],
    policies: {
      refundable: true,
      transferable: true,
    },
    status: "published",
    createdAt: "2025-01-01T00:00:00",
  },
  {
    id: "evt-3",
    title: "TIS Conference",
    slug: "tis-conference",
    category: "Conference",
    image: "https://example.com/images/tis-conference.jpg",
    description: "A conference for technology and innovation specialists.",
    venue: "Convention Center",
    city: "Ho Chi Minh City",
    date: "2025-09-30",
    time: "09:00",
    organizerId: "org-2",
    organizerName: "Tech Innovation Society",
    ticketTiers: [
      {
        id: "tier-7",
        name: "Standard Pass",
        price: 2500000,
        available: 30,
        total: 30,
      },
    ],
    policies: {
      refundable: false,
      transferable: true,
    },
    status: "published",
    createdAt: "2025-01-01T00:00:00",
  },
  {
    id: "evt-4",
    title: "Art Exhibition",
    slug: "art-exhibition",
    category: "Arts",
    image: "https://example.com/images/art-exhibition.jpg",
    description:
      "An exhibition showcasing contemporary art from various artists.",
    venue: "National Art Gallery",
    city: "Hanoi",
    date: "2025-10-15",
    time: "10:00",
    organizerId: "org-3",
    organizerName: "National Art Gallery",
    ticketTiers: [
      {
        id: "tier-8",
        name: "VIP Pass",
        price: 5000000,
        available: 10,
        total: 10,
      },
    ],
    policies: {
      refundable: true,
      transferable: false,
    },
    status: "published",
    createdAt: "2025-01-01T00:00:00",
  },
];

export const mockOrders: Order[] = [
  {
    id: "ord-1",
    userId: "user-1",
    eventId: "evt-1",
    tickets: [
      {
        id: "tkt-1",
        tierId: "tier-1",
        tierName: "General Admission",
        price: 500000,
        qrCode: "QR-SMF-GA-001",
        status: "valid",
      },
      {
        id: "tkt-2",
        tierId: "tier-1",
        tierName: "General Admission",
        price: 500000,
        qrCode: "QR-SMF-GA-002",
        status: "valid",
      },
    ],
    subtotal: 1000000,
    serviceFee: 50000,
    total: 1050000,
    status: "completed",
    createdAt: "2025-10-15T10:30:00",
    userEmail: "user@example.com",
    userName: "Nguyen Van A",
    paymentMethod: "Visa •••• 4242",
  },
  {
    id: "ord-2",
    userId: "user-1",
    eventId: "evt-2",
    tickets: [
      {
        id: "tkt-3",
        tierId: "tier-6",
        tierName: "Category A",
        price: 800000,
        qrCode: "QR-VNM-THA-001",
        status: "valid",
        seatInfo: "Section A, Row 5, Seat 12",
      },
    ],
    subtotal: 800000,
    serviceFee: 40000,
    total: 840000,
    status: "completed",
    createdAt: "2025-10-20T14:15:00",
    userEmail: "user@example.com",
    userName: "Nguyen Van A",
    paymentMethod: "MoMo",
  },
  {
    id: "ord-3",
    userId: "user-1",
    eventId: "evt-3",
    tickets: [
      {
        id: "tkt-4",
        tierId: "tier-7",
        tierName: "Standard Pass",
        price: 2500000,
        qrCode: "QR-TIS-STD-001",
        status: "valid",
      },
    ],
    subtotal: 2500000,
    serviceFee: 125000,
    total: 2625000,
    status: "completed",
    createdAt: "2025-10-25T09:00:00",
    userEmail: "user@example.com",
    userName: "Nguyen Van A",
    paymentMethod: "VNPay",
  },
];

export const mockWishlist: WishlistItem[] = [
  {
    id: "wish-1",
    userId: "user-1",
    eventId: "evt-1",
    addedAt: "2025-10-01T10:00:00",
  },
  {
    id: "wish-2",
    userId: "user-1",
    eventId: "evt-3",
    addedAt: "2025-10-05T14:30:00",
  },
  {
    id: "wish-3",
    userId: "user-1",
    eventId: "evt-4",
    addedAt: "2025-10-10T08:15:00",
  },
];

export const mockWaitlist: WaitlistEntry[] = [
  {
    id: "wait-1",
    userId: "user-1",
    eventId: "evt-1",
    position: 15,
    status: "active",
    joinedAt: "2025-11-01T10:00:00",
    estimatedNotification: "2025-12-01",
  },
  {
    id: "wait-2",
    userId: "user-1",
    eventId: "evt-2",
    position: 1,
    status: "notified",
    joinedAt: "2025-10-28T16:20:00",
    estimatedNotification: "2025-11-15",
  },
  {
    id: "wait-3",
    userId: "user-1",
    eventId: "evt-3",
    position: 0,
    status: "expired",
    joinedAt: "2025-10-01T12:00:00",
  },
];
